### ISSUE TITLE
switch to .less

### ISSUE THREAD

**Issue by pYr0x** [donejs/donejs-react#5]
since the steal-sass plugin is not very good at the moment, i would like to switch to .less.
it is consistent to the other generators.
and with less we have this cool feature of `locate`

**Comment by matthewp** [comment]
This is a generator, I'm not sure why it's installing a css preprocessor at all. That seems pretty unrelated to React.

**Comment by pYr0x** [comment]
but the component generator for canjs does also provide a css preprocessor 
https://github.com/donejs/generator-donejs/blob/master/component/templates/modlet/component.js#L4

**Comment by matthewp** [comment]
Fair point, the question is "what is donejs-react"?  DoneJS is an opinionated client-side framework.  It comes with some stuff like QUnit as well as Less.

So what is "donejs-react"?  I see it as a plugin on top of DoneJS similar to donejs-cordova. It is to add React on top of a base DoneJS project. 

Going back to the QUnit example, @phillipskevin is working on making it so that you can do `donejs add mocha` and from that point on the tests you generate would be Mocha tests instead of QUnit.  In the same way there could be a `donejs add sass` that replaces the less components that usually get generated with sass ones.

I like this approach because DoneJS comes with certain defaults (Stache, QUnit, Less) and then you can use these various generators to swap out the parts.

**Comment by pYr0x** [comment]
ok i am with you.

should i make a PR and remove sass and add less instead?

**Comment by matthewp** [comment]
You wouldn't need to add less, DoneJS already comes with less support (because Steal does).  Anyways, the above are just my opinions, this is not my project :)  @Alfredo-Delgado @moschel @DesignByOnyx ?
